import React from 'react';
import type { Metadata } from 'next';
import { SessionProvider } from 'next-auth/react';
import { Tourney, Open_Sans } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';

const tourney = Tourney({
  weight: '400',
  subsets: ['latin'],
});

const openSans = Open_Sans({
  weight: ['400', '600', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'CoachUP',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={openSans.className}>
      <body>
        <SessionProvider>
          <Header />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
